type: object
properties: 
  id: 
    type: string
    format: uuid
    description: The unique identifier of the image
    nullable: true
  url:
    type: string
    format: url
    description: The url of the image 
    minLength: 5
    maxLength: 500
    example: https://host/image.jpg
  altText:
    type: string
    nullable: true
    minLength: 3
    maxLength: 255 
required: 
  -  url  
  -  id 