openapi: 3.0.3
info:
  version: 1.0.0
  title: API First with Spring Boot
  termsOfService: https://example.com/terms/
  contact:
    email: email@email.com
    url: https://toniferr.github.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification.
tags:
  - name: Customer
    description: Customer operations
  - name: Product
    description: Product operations   
  - name: Order
    description: Operations about orders.
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://host/api/v1
paths:
  /v1/customers:
    $ref: paths/v1/customers.yaml
  /v1/customers/{customerId}:
    $ref: paths/v1/customers_{customerId}.yaml
  /v1/products:
    $ref: paths/v1/products.yaml
  /v1/products/{productId}:
    $ref: paths/v1/products_{productId}.yaml    
  /v1/orders:
    $ref: paths/v1/orders.yaml
  /v1/orders/{orderId}:
    $ref: paths/v1/orders_{orderId}.yaml
  /v1/categories:
    $ref: paths/v1/categories.yaml  
security: 
  -  basic_auth: []  
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
